server:
  port: 8080
  servlet:
    context-path: /api
spring:
  properties:
    host-name: ${APP_HOST_NAME}
    github:
      token: ${GithubBearer}
    async:
      max-pool-size: 10
      core-pool-size: 5
    feature-enabled:
      auto-upload: ${AUTO_UPLOAD_ENABLED:true}
      auto-upload-meta: ${AUTO_UPLOAD_META_ENABLED:false}
      feed-generation: ${FEED_GENERATION_ENABLED:false}
      request-logging: ${REQUEST_LOGGING_ENABLED:false}
    auto-upload:
      period-mills: 3600000 # 1 hour
      core-pool-size: 3
      query-per-second: 3
    db:
      schema: gfi
    cyclonedx:
      ports:
        - 9090
        - 9091
        - 9092
        - 9093
        - 9094
    email:
      username: ${EMAIL_USERNAME}
      password: ${EMAIL_PASSWORD}
  flyway:
    enabled: true
    clean-disabled: true
    encoding: UTF-8
    locations: classpath:db/migration
    sql-migration-prefix: V
    sql-migration-separator: __
    sql-migration-suffixes: .sql
    validate-on-migrate: true
    baseline-on-migrate: true
    url: ${spring.datasource.url}
    password: ${spring.datasource.password}
    user: ${spring.datasource.username}
  application:
      name: good-first-issue-back
  datasource:
    password: SomeUselessPassword02
    url: jdbc:postgresql://${spring.properties.host-name}:5432/uj?currentSchema=${spring.properties.db.schema}
    username: idk_user
  jpa:
    hibernate:
      ddl-auto: validate

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.github.regyl.gfi.controller.dto
  type-handlers-package: com.github.regyl.gfi.typehandler

logging:
  level:
    root: info